// SPDX-License-Identifier: Apache-2.0
package me.jxl.kiosk.plugins.flights.enrich;

import java.util.HashMap;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Airline names by ICAO prefix, for when the route lookup has not answered (or missed). Names only:
 * the renderer owns chip colours. Facts, written by us (docs/DATA-SOURCES.md).
 */
public final class Airlines {
  private static final Pattern AIRLINE_CALLSIGN = Pattern.compile("^([A-Z]{3})\\d{1,4}[A-Z]{0,2}$");
  private static final Map<String, String> NAMES = new HashMap<>();

  static {
    String[] t = {
      "AAL",
      "American Airlines",
      "DAL",
      "Delta Air Lines",
      "UAL",
      "United Airlines",
      "SWA",
      "Southwest Airlines",
      "JBU",
      "JetBlue",
      "ASA",
      "Alaska Airlines",
      "NKS",
      "Spirit Airlines",
      "FFT",
      "Frontier Airlines",
      "AAY",
      "Allegiant Air",
      "HAL",
      "Hawaiian Airlines",
      "SKW",
      "SkyWest",
      "RPA",
      "Republic Airways",
      "ENY",
      "Envoy Air",
      "PDT",
      "Piedmont Airlines",
      "EDV",
      "Endeavor Air",
      "ASQ",
      "ExpressJet",
      "JIA",
      "PSA Airlines",
      "GJS",
      "GoJet Airlines",
      "FDX",
      "FedEx",
      "UPS",
      "UPS Airlines",
      "GTI",
      "Atlas Air",
      "ABX",
      "ABX Air",
      "CPZ",
      "Compass Airlines",
      "SCX",
      "Sun Country",
      "VXP",
      "Avelo Airlines",
      "BAW",
      "British Airways",
      "DLH",
      "Lufthansa",
      "AFR",
      "Air France",
      "KLM",
      "KLM",
      "UAE",
      "Emirates",
      "QFA",
      "Qantas",
      "ACA",
      "Air Canada",
      "WJA",
      "WestJet",
      "AMX",
      "Aeromexico",
      "VOI",
      "Volaris",
      "JAL",
      "Japan Airlines",
      "ANA",
      "All Nippon Airways",
      "SIA",
      "Singapore Airlines",
      "CPA",
      "Cathay Pacific",
      "KAL",
      "Korean Air",
      "THY",
      "Turkish Airlines",
      "EJA",
      "NetJets",
      "LXJ",
      "Flexjet",
      "AWI",
      "Air Wisconsin",
      "QXE",
      "Horizon Air",
      "CMP",
      "Copa Airlines",
      "AVA",
      "Avianca",
      "LAN",
      "LATAM Chile",
      "LPE",
      "LATAM Peru",
      "AZU",
      "Azul",
      "GLO",
      "Gol",
      "ICE",
      "Icelandair",
      "MXY",
      "Breeze Airways",
      "OCN",
      "Discover Airlines",
      "VIV",
      "Viva Aerobus",
      "ASH",
      "Mesa Airlines",
      "KAP",
      "Cape Air",
      "AMF",
      "Ameriflight",
      "TSC",
      "Air Transat",
      "CUB",
      "Cubana",
      "BHS",
      "Bahamasair",
      "CAY",
      "Cayman Airways",
      "EIN",
      "Aer Lingus",
      "SAS",
      "SAS Scandinavian Airlines",
      "IBE",
      "Iberia",
      "AEA",
      "Air Europa",
      "TAP",
      "TAP Air Portugal",
      "SWR",
      "Swiss",
      "AUA",
      "Austrian Airlines",
      "BEL",
      "Brussels Airlines",
      "FIN",
      "Finnair",
      "LOT",
      "LOT Polish Airlines",
      "NAX",
      "Norwegian",
      "ETD",
      "Etihad Airways",
      "QTR",
      "Qatar Airways",
      "ELY",
      "El Al",
      "ETH",
      "Ethiopian Airlines",
      "ARG",
      "Aerolineas Argentinas",
      "TAM",
      "LATAM Brasil",
      "EDW",
      "Edelweiss",
      "GEC",
      "Lufthansa Cargo",
      "CLX",
      "Cargolux",
      "CKS",
      "Kalitta Air",
      "ATN",
      "Air Transport International",
      "AJT",
      "Amerijet",
      "JRE",
      "flyExclusive",
    };
    for (int i = 0; i < t.length; i += 2) NAMES.put(t[i], t[i + 1]);
  }

  private Airlines() {}

  /** The three-letter ICAO prefix of an airline-style callsign (DAL800 -> DAL), else null. */
  public static String prefix(String callsign) {
    if (callsign == null) return null;
    Matcher m = AIRLINE_CALLSIGN.matcher(callsign);
    return m.matches() ? m.group(1) : null;
  }

  /** Name for an ICAO prefix, or null when it is not in the table. */
  public static String name(String icao) {
    return icao == null ? null : NAMES.get(icao);
  }
}
