#!/usr/bin/env python3
"""Bundle assets/flights into one HTML string for inline delivery, as Java source.

Inline publishes swap into the live WebView without a flash, but the plugin's Java
cannot read packaged assets, so the page is compiled in. The `/*PAYLOAD*/` slot is kept.
Usage: scripts/bundle-page.py
"""
import json, pathlib, re

root = pathlib.Path(__file__).resolve().parent.parent
src = root / "assets" / "flights"
out = root / "src" / "me" / "jxl" / "kiosk" / "plugins" / "flights" / "FlightsHtml.java"

html = (src / "index.html").read_text()
html = re.sub(r'<link rel="stylesheet" href="style.css">',
              lambda m: "<style>" + (src / "style.css").read_text() + "</style>", html)
html = re.sub(r'<script src="(icons|lib|render).js"></script>',
              lambda m: "<script>" + (src / (m.group(1) + ".js")).read_text() + "</script>", html)
assert "/*PAYLOAD*/" in html and 'src="' not in html.replace('src="data', ""), "bundle is not self-contained"

lit = lambda c: '"' + c.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n") + '"'
chunks = lambda t: ",\n        ".join(lit(t[i:i + 12000]) for i in range(0, len(t), 12000))  # javac 64 KiB constant limit
out.write_text(
    "// Generated by scripts/bundle-page.py from assets/flights. Do not edit.\n"
    "package me.jxl.kiosk.plugins.flights;\n\nfinal class FlightsHtml {\n"
    f"    private static final String[] PAGE = {{\n        {chunks(html)}\n    }};\n\n"
    "    static String html() {\n        return String.join(\"\", PAGE);\n    }\n}\n")
print(f"page {len(html)} B")
