#!/usr/bin/env python3
"""Compile an OurAirports airports.csv subset into src/.../flights/AirportData.java.

Keeps large airports plus medium airports with scheduled service, each with a code (IATA, else
ICAO ident). Records are "CODE lat lon size" joined by ';' (size 2 large, 1 medium), chunked for
javac's 64 KiB constant limit. OurAirports is public domain (docs/DATA-SOURCES.md).
Usage: scripts/gen-airports.py path/to/airports.csv
"""
import csv, pathlib, sys

out = pathlib.Path(__file__).resolve().parent.parent / "src/me/jxl/kiosk/plugins/flights/AirportData.java"
recs = []
for a in csv.DictReader(open(sys.argv[1], newline="", encoding="utf-8")):
    large = a["type"] == "large_airport"
    if not (large or (a["type"] == "medium_airport" and a["scheduled_service"] == "yes")):
        continue
    code = a["iata_code"] or a["icao_code"] or a["ident"]
    if not code or not code.isalnum():
        continue
    recs.append(f'{code} {float(a["latitude_deg"]):.3f} {float(a["longitude_deg"]):.3f} {2 if large else 1}')
recs.sort()
text = ";".join(recs)
lit = lambda c: '"' + c.replace("\\", "\\\\").replace('"', '\\"') + '"'
chunks = ",\n        ".join(lit(text[i:i + 12000]) for i in range(0, len(text), 12000))
out.write_text(
    "// Generated by scripts/gen-airports.py from OurAirports. Do not edit.\n"
    "package me.jxl.kiosk.plugins.flights;\n\nfinal class AirportData {\n"
    f"    private static final String[] DATA = {{\n        {chunks}\n    }};\n\n"
    "    static String records() {\n        return String.join(\"\", DATA);\n    }\n}\n")
print(f"{len(recs)} airports, {len(text)} B")
