#!/usr/bin/env python3
"""Embed an asset page into Java as a string, for inline publishing.

Inline publishes update the live WebView without recreating it, but the
plugin's Java cannot read packaged assets, so the page is compiled in.
Usage: scripts/gen-inline.py assets/spike/index.html src/.../SpikeHtml.java com.pkg ClassName
"""
import sys, pathlib
src, out, pkg, cls = sys.argv[1:5]
html = pathlib.Path(src).read_text()
chunks = [html[i:i + 12000] for i in range(0, len(html), 12000)]  # javac's 65535-byte constant limit
lit = lambda c: '"' + c.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n") + '"'
body = ",\n        ".join(lit(c) for c in chunks)
pathlib.Path(out).write_text(
    f"// Generated by scripts/gen-inline.py from {src}. Do not edit.\n"
    f"package {pkg};\n\nfinal class {cls} {{\n"
    f"    static final String[] PARTS = {{\n        {body}\n    }};\n\n"
    f"    static String html() {{\n        return String.join(\"\", PARTS);\n    }}\n}}\n")
