#!/usr/bin/env python3
"""Embed the chosen ADS-B Radar aircraft icons into assets/flights/icons.js as plain SVG strings.

Usage: scripts/gen-icons.py <folder with the pack's .svg files>
Icons by ADS-B Radar for macOS - https://adsb-radar.com (free with a backlink; see docs/DATA-SOURCES.md).
The pack's files differ (rotations, ellipses, several shapes), so they are embedded as they are,
minified and with the editor-only bx: metadata removed, and the WebView draws them. They are used
as an alpha mask and tinted at runtime, so the pack's own fill colour does not matter.
"""
import json, pathlib, re, sys

KEYS = ("a0 a320 a330 a340 a380 a4 a7 b737 b747 b767 b777 b787 beechcraft c130 cessna crjx dh8a e195 "
        "erj f100 fa7x glf5 learjet md11 heavyfreighter").split()
src = pathlib.Path(sys.argv[1])
out = pathlib.Path(__file__).resolve().parent.parent / "assets" / "flights" / "icons.js"


def clean(t):
    t = re.sub(r"<\?xml.*?\?>|<!DOCTYPE.*?>|<!--.*?-->", "", t, flags=re.S)
    t = re.sub(r"<bx:[^>]*?/>|<bx:.*?</bx:[^>]*>", "", t, flags=re.S)
    t = re.sub(r'\sxmlns:bx="[^"]*"|\sbx:[\w-]+="[^"]*"', "", t)
    t = re.sub(r'(<svg[^>]*?)\swidth="[^"]*"', r"\1", t, count=1)
    t = re.sub(r'(<svg[^>]*?)\sheight="[^"]*"', r"\1", t, count=1)
    t = t.replace("<svg", '<svg width="128" height="128"', 1)
    return re.sub(r"\s+", " ", t).strip()


icons = {k: clean((src / f"{k}.svg").read_text()) for k in KEYS}
out.write_text(
    "// Aircraft silhouettes (nose up), embedded SVG used as an alpha mask and tinted per airline.\n"
    "// Icons by ADS-B Radar for macOS - https://adsb-radar.com (free with a backlink; see docs/DATA-SOURCES.md).\n"
    "// Generated by scripts/gen-icons.py. Do not edit.\n"
    "const ICONS = " + json.dumps(icons, indent=1) + ";\n")
print(f"{len(icons)} icons, {out.stat().st_size} B")
